# Generated by Django 4.2 on 2023-05-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK99ZJCRNR_DJqeV7VfPMYcC9md4WtH3ItB8trBQfkbenGHxai-xmq7QqVxGWjG41mGwZBTCwcEYQ&usqp=CAU&ec=48665698', max_length=500),
        ),
    ]
